### ISSUE TITLE
 Could not get message store services. Maybe the message store has not been started? Retrying

### ISSUE THREAD

**Issue by alirezaahmadi** [LCAS/topological_navigation#22]
Hi I am trying to run the "roslaunch topological_navigation topological_navigation_empty_map.launch map:='name_of_topological_map'" and every time this message comes up, I wanted to test the topological navigation in the simulator first, is it possible ?? 

best,
Alireza (from university of Bonn)

**Comment by gpdas** [comment]
It is possible to load topomap in simulation.
Until very recently the topomap was loaded from a mongodb to the map manager. This error message is coming because the `mongodb_store` nodes are not started properly. 

Follow the instructions in [this page](https://github.com/strands-project/strands_navigation/wiki/Quick-Topological-Navigation-in-simulation-tutorial)

Loading topomaps directly from files to `map_manager` is being worked on at the moment. Not all functionalities are ready yet.

**Comment by gpdas** [comment]
@alirezaahmadi I assume this is sorted by following tutorials on strands_navigation wiki.

Closing this now. Please re-open, if the problem persists.
